### PR TITLE
fix: remove the use of asyncio.get_child_watcher() for python3.14

### LINKED ISSUE #583: broken on python3.14 ('asyncio' has no attribute 'get_child_watcher')
Hi,

unfortunatelly pynvim seems to be broken on 3.14

```python

Traceback (most recent call last):
  File "/Users/user/work/my/ylib/sandbox/py/nvim/t.py", line 2, in <module>
    nvim = pynvim.attach('child', argv=["/usr/bin/env", "nvim", "--embed", "--headless"])
  File "/Users/user/.local/venv/python3.14/lib/python3.14/site-packages/pynvim/__init__.py", line 144, in attach
    child_session(cast(List[str], argv)) if session_type == 'child' else
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.local/venv/python3.14/lib/python3.14/site-packages/pynvim/msgpack_rpc/__init__.py", line 49, in child_session
    return session('child', argv)
  File "/Users/user/.local/venv/python3.14/lib/python3.14/site-packages/pynvim/msgpack_rpc/__init__.py", line 23, in session
    loop = EventLoop(transport_type, *args, **kwargs)
  File "/Users/user/.local/venv/python3.14/lib/python3.14/site-packages/pynvim/msgpack_rpc/event_loop/asyncio.py", line 132, in __init__
    super().__init__(transport_type, *args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.local/venv/python3.14/lib/python3.14/site-packages/pynvim/msgpack_rpc/event_loop/base.py", line 109, in __init__
    raise e
  File "/Users/user/.local/venv/python3.14/lib/python3.14/site-packages/pynvim/msgpack_rpc/event_loop/base.py", line 106, in __init__
    getattr(self, '_connect_{}'.format(transport_type))(*args, **kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/user/.local/venv/python3.14/lib/python3.14/site-packages/pynvim/msgpack_rpc/event_loop/asyncio.py", line 201, in _connect_child
    self._child_watcher = asyncio.get_child_watcher()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'get_child_watcher'




```

### PR DESCRIPTION
**Pull request by cryptomilk**
Use PidfdChildWatcher if os.pidfd_open is available and works, and otherwise use ThreadedChildWatcher which should work in any case.

Fixes #583

### CODE REVIEW

**Comment by cryptomilk** [comment]
Looks like that the CI fails before it runs the tests.

**Comment by justinmk** [comment]
expand this to see the test failures:

image

```
 FAILED test/test_buffer.py::test_options - OSError: EOF
  FAILED test/test_buffer.py::test_get_exceptions - OSError: EOF
  FAILED test/test_window.py::test_options - OSError: EOF
```

**Comment by wookayin** [comment]
I will send a separate PR to fix a failure on python 3.13.

**Comment by cryptomilk** [comment]
Oh, locally I'm running nvim 0.10.3 and everything works. GH runs nvim nightly?

**Comment by cryptomilk** [comment]
I've rebased on master and it shows that the patch works fine with nvim-stable but fails with nvim-nightly.

**Comment by justinmk** [comment]
windows ci shows an issue:

```
  C:\hostedtoolcache\windows\Python\3.13.1\x64\Lib\asyncio\unix_events.py:40: in <module>
      raise ImportError('Signals are not really supported on Windows')
  E   ImportError: Signals are not really supported on Windows
```

other than that, the failing `vim.current.buffer.options['invalid-option']` tests are a known issue 

> Note: Tests are still failing on nvim-nightly due to upstream bug, but as soon as [neovim/neovim#31894](https://github.com/neovim/neovim/issues/31894) is fixed CI should be back to green.

**Comment by cryptomilk** [comment]
Maybe we need to make sure the ThreadedChildWatcher is used on Windoze?

File: pynvim/msgpack_rpc/event_loop/asyncio.py [hunk 1]
```diff
@@ -188,18 +193,33 @@ async def connect_stdout():
...
             pid = transport.get_pid()
             debug("child subprocess_exec successful, PID = %s", pid)
 
+            if os.name != 'nt':
+                # see #238, #241
+                pidfd_works = False
+                if PidfdChildWatcher is not None and hasattr(os, "pidfd_open"):
+                    try:
+                        fd = os.pidfd_open(pid)
+                    except Exception:
```
Comment (wookayin) [inline pynvim/msgpack_rpc/event_loop/asyncio.py:209]: Out of curiosity, under which settings can the `pidfd_open` syscall fail?

Comment (cryptomilk) [reply pynvim/msgpack_rpc/event_loop/asyncio.py:209]: It is a Linux syscall. So on Linux < 5.3 or BSD.

Comment (wookayin) [reply pynvim/msgpack_rpc/event_loop/asyncio.py:209]: On Linux < 5.3, `os.pidfd_open` won't exist at all. Precisely what exceptions are being caught, and when does it *fail* (while exists)?

Comment (cryptomilk) [reply pynvim/msgpack_rpc/event_loop/asyncio.py:209]: Invalid pid, pid already dead, not sure if a pid is a zombie. Are we sure transport.get_pid() only returned a valid working pid?

File: pynvim/msgpack_rpc/event_loop/asyncio.py [hunk 2]
```diff
@@ -188,18 +193,33 @@ async def connect_stdout():
...
+                        pass
+                    else:
+                        os.close(fd)
+                        pidfd_works = True
+
+                if pidfd_works:
+                    watcher = PidfdChildWatcher()
+                else:
+                    watcher = ThreadedChildWatcher()
```
Comment (wookayin) [inline pynvim/msgpack_rpc/event_loop/asyncio.py:218]: Just noting: ThreadedChildWatcher requires python 3.8+, PidfdChildWatcher requires python 3.9+. While we might want to drop support for python3.7, we could also simply fall back to `get_child_watcher` if neither exists.

I would suggest extracting these lines into an inner helper function (say `get_child_watcher`) and return either `PidfdChildWatcher`, `ThreadedChildWatcher`, or `asyncio.get_child_watcher()` as a fallback.

**Review by justinmk — APPROVED** [review]

**Comment by cryptomilk** [comment]
I'm sick, it has to wait ...

**Comment by justinmk** [comment]
If necessary, we can drop python 3.7 support.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/31894 was fixed, will re-run the tests here after a new nightly is posted.

**Comment by cryptomilk** [comment]
Rebased, tests are mostly passing now. The Windows and MacOS tests with Python 3.13 are failing.

On Windows it looks like we have some closing workaround which fails with Python 3.13 now.
https://github.com/neovim/pynvim/blob/9c5ec674453a9742c141d201153bd12b73846355/pynvim/msgpack_rpc/event_loop/asyncio.py#L250

I have no idea what is wrong on MacOS.

**Comment by cryptomilk** [comment]
I added a commit which disabled the workaround on Windows and that seems to work. Not sure if this is the right fix. I have no clue about Windows.

The failing test_attach.py::test_connect_stdioThe test on MacOS seems to be race condition. Now it works on 3.13 and fails on 3.12.

**Comment by wookayin** [comment]
I don't think the macOS failure has something to do with this PR; it'll be a different bug that already existed. I'll see later if we can bring a proper fix.

**Comment by justinmk** [comment]
> disabled the workaround on Windows and that seems to work

that was added in https://github.com/neovim/pynvim/commit/17fbcbccde9978a5caa05f571174bfff4a0b7bdd ; @wookayin do you see any risk with disabling it here?

**Review by justinmk — APPROVED** [review]

File: pynvim/msgpack_rpc/event_loop/asyncio.py [hunk 3]
```diff
@@ -188,10 +188,42 @@ async def connect_stdout():
...
+                os.close(fd)
+            except OSError:
+                return False
+
+            return True
+
+        def get_child_watcher():
+            if can_use_pidfd():
+                try:
+                    from asyncio.unix_events import PidfdChildWatcher
```
Comment (wookayin) [inline pynvim/msgpack_rpc/event_loop/asyncio.py:209]:
```suggestion
                try:
                    from asyncio import PidfdChildWatcher, ThreadedChildWatcher
                    return PidfdChildWatcher()
                except ImportError:
                    # FIXME Python 3.7, return None if we drop support
                    return asyncio.get_child_watcher()
                     
```

On python3.14 (macos), `asyncio.unix_events.PidfdChildWatcher` symbol does not exist; there is only `_PidfdChildWatcher`.

**Review by wookayin — CHANGES_REQUESTED** [review]

File: pynvim/msgpack_rpc/event_loop/asyncio.py (hunk 3 above)
Comment (cryptomilk) [reply pynvim/msgpack_rpc/event_loop/asyncio.py:209]: Are you sure that `can_use_pidfd()` returns `True` on MacOS?

File: pynvim/msgpack_rpc/event_loop/asyncio.py [hunk 4]
```diff
@@ -250,7 +282,8 @@ def _close_transport(transport):
             # Windows: for ProactorBasePipeTransport, close() doesn't take in
             # effect immediately (closing happens asynchronously inside the
             # event loop), need to wait a bit for completing graceful shutdown.
-            if os.name == 'nt' and hasattr(transport, '_sock'):
+            if (sys.version_info.major == 3 and sys.version_info.minor < 13 and
+                    os.name == 'nt' and hasattr(transport, '_sock')):
```
Comment (wookayin) [inline pynvim/msgpack_rpc/event_loop/asyncio.py:286]:
```suggestion
            if sys.version_info < (3, 13) and os.name == 'nt' and hasattr(transport, '_sock')):
```

(though python 4.13 is too far in the future..)

In replying to https://github.com/neovim/pynvim/pull/584#issuecomment-2583355719: I haven't tested on Windows + python3.13, but I remember for older python versions this is still necessary.

**Comment by wookayin** [comment]
I cherry-picked the commit eb14e83 for bumping up msgpack as it's a bit tangential to this fix.

Regarding the workaround in 17fbcbccde9978a5caa05f571174bfff4a0b7bdd, we can try disabling the workaround for python3.13 on Windows to see if the bug has been fixed. But I believe for older versions this workaround will still be necessary.

File: pynvim/msgpack_rpc/event_loop/asyncio.py (hunk 3 above)
Comment (wookayin) [reply pynvim/msgpack_rpc/event_loop/asyncio.py:209]: Actually no. Though symbols can be imported, I agree they won't work.

```python
>>> from asyncio.unix_events import can_use_pidfd
>>> can_use_pidfd()
False
>>> from asyncio import PidfdChildWatcher
ImportError: cannot import name 'PidfdChildWatcher' from 'asyncio'

>>> from asyncio.unix_events import _PidfdChildWatcher
>>> _PidfdChildWatcher()
<asyncio.unix_events._PidfdChildWatcher object at 0x105d11010>

>>> from asyncio.unix_events import _ThreadedChildWatcher
>>> _ThreadedChildWatcher()
<asyncio.unix_events._ThreadedChildWatcher object at 0x105d10c20>
```
and same for `ThreadedChildWatcher`. In the source code of python3.14 alpha distribution for macOS, those watcher classes are prefixed in `_`. So I think `asyncio.unix_events` is fine but platform-dependent. 

On my macOS python3.14 env, it falled back to `asyncio.get_child_watcher()` and error again (it's gone). It seems that our current fix works for Linux, but I'm not yet sure about macOS.

File: pynvim/msgpack_rpc/event_loop/asyncio.py (hunk 4 above)
Comment (cryptomilk) [reply pynvim/msgpack_rpc/event_loop/asyncio.py]: I added this. Thanks.

File: pynvim/msgpack_rpc/event_loop/asyncio.py (hunk 3 above)
Comment (cryptomilk) [reply pynvim/msgpack_rpc/event_loop/asyncio.py]: Ah, I see. Pushed a fix.

Comment (wookayin) [reply pynvim/msgpack_rpc/event_loop/asyncio.py]: Thanks. I know it's not easy to reproduce from your end, but somehow  `asyncio.ThreadedChildWatcher` does not exist in python3.14. So it still falls back to `asyncio.get_child_watcher()` :/  I guess this is a regression in python3.14 dev versions --- because this works in python3.13 for me.

Since python3.14 is not a stable/released version, this shouldn't be a major blocker.

**Comment by cryptomilk** [comment]
I really start to hate Python.

https://github.com/python/cpython/commit/9d2e1ea3862e5950d48b45ac57995a206e33f38b
https://github.com/python/cpython/issues/120804

Every 2 versions they completely break the API. WTF.

**Comment by cryptomilk** [comment]
Looks like supporting 3.14 is a much bigger rewrite.

**Comment by wookayin** [comment]
I appreciate your patience. Now as I think about the role of child_watcher, it's not quite crucial part of the pynvim functionality and I think we actually don't need it other than preventing resource leak when the event loop closes.

Let's make our life simpler and easier: my proposal is to simply just disable child_watcher in python3.14 (i.e. set `child_watcher = None`), and let pynvim just work for python3.14.

**Comment by cryptomilk** [comment]
Looks like I misunderstood how things are now. I hope this patch fixes it now.

File: pynvim/msgpack_rpc/event_loop/asyncio.py [hunk 5]
```diff
@@ -188,10 +188,19 @@ async def connect_stdout():
...
+        def get_child_watcher():
+            try:
+                return asyncio.get_child_watcher()
+            except AttributeError:  # Python 3.14
+                return None
+
+            return None
+
         if os.name != 'nt':
-            # see #238, #241
```
Comment (wookayin) [inline pynvim/msgpack_rpc/event_loop/asyncio.py:192]: Let's keep this comment?

**Review by wookayin — APPROVED** [review]

File: pynvim/msgpack_rpc/event_loop/asyncio.py (hunk 5 above)
Comment (cryptomilk) [reply pynvim/msgpack_rpc/event_loop/asyncio.py:192]: I added it back.

**Comment by justinmk** [comment]
Thank you both!
